source 'https://github.com/CocoaPods/Specs.git'
project 'Chef.xcodeproj'
platform :ios, '7.0'
use_frameworks!
target 'Chef' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for FH
  #pod 'FH', '~> 3.1.1'
  pod 'RCTFH', path: '../node_modules/rct-fh'
end