// leave off @2x/@3x
const images = {
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  cauldron: require('../Images/cauldron.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  michelinStar: require('../Images/Icons/michelin-star.png'),
  laListe: require('../Images/Icons/la-liste.png'),
  ingredients: require('../Images/ingredients.jpg'),
  directions: require('../Images/directions.jpg'),
  kitchen: require('../../../App/Images/kitchen-blue.png'),
  pepper: require('../../../App/Images/pepper.png'),
  presentation: require('../../../App/Images/background-wood.png'),
  MEDIUM_RED: require('../../../App/Images/MEDIUM_RED.png'),
  BOLD_RED: require('../../../App/Images/BOLD_RED.png'),
  DESSERT: require('../../../App/Images/DESSERT.png'),
  ROSE: require('../../../App/Images/ROSE.png'),
  LIGHT_RED: require('../../../App/Images/LIGHT_RED.png'),
  SPARKLING: require('../../../App/Images/SPARKLING.png'),
  SWEET_WHITE: require('../../../App/Images/SWEET_WHITE.png'),
  DRY_WHITE: require('../../../App/Images/DRY_WHITE.png'),
  RICH_WHITE: require('../../../App/Images/RICH_WHITE.png'),
  bottle_with_a_heart: require('../../../App/Images/bottle-with-a-heart.png'),
}

export default images
